[package]
name = "just-call-version"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
windows = { version = "0.48.0", features = ["Win32_Storage_FileSystem", "Win32_Foundation", "Win32_Media_Audio"] }
widestring = "1.0.2"
